"""initial migration

Revision ID: 6891261274ff
Revises: 
Create Date: 2025-06-10 10:32:02.432652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6891261274ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spots', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=1),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('spot_number')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('parking_timestamp', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('expected_end_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('leaving_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('parking_cost', sa.Float(), nullable=True))
        batch_op.drop_column('end_time')
        batch_op.drop_column('status')
        batch_op.drop_column('start_time')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('pincode',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('user_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('pincode',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('parking_cost')
        batch_op.drop_column('leaving_timestamp')
        batch_op.drop_column('expected_end_time')
        batch_op.drop_column('parking_timestamp')
        batch_op.drop_column('vehicle_number')

    with op.batch_alter_table('parking_spots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spot_number', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.String(length=1),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
